-- MySQL Script generated by MySQL Workbench
-- Mon Nov 10 14:12:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Piloto` (
  `idPiloto` INT NOT NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPiloto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piloto` (
  `idPiloto` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Clave` VARCHAR(45) NULL,
  `Foto` VARCHAR(100) NULL,
  `Estado_Piloto_idPiloto` INT NOT NULL,
  PRIMARY KEY (`idPiloto`),
  INDEX `fk_piloto_Estado_Piloto1_idx` (`Estado_Piloto_idPiloto` ASC) VISIBLE,
  CONSTRAINT `fk_piloto_Estado_Piloto1`
    FOREIGN KEY (`Estado_Piloto_idPiloto`)
    REFERENCES `mydb`.`Estado_Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasajero` (
  `idPasajero` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Clave` VARCHAR(45) NULL,
  PRIMARY KEY (`idPasajero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avion` (
  `Matricula` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Capacidad` INT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ruta` (
  `idRuta` INT NOT NULL,
  `Origen` VARCHAR(100) NULL,
  `Destino` VARCHAR(100) NULL,
  `Duracion_Estimada` TIME NULL,
  `Distancion_KM` VARCHAR(45) NULL,
  PRIMARY KEY (`idRuta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Vuelo` (
  `idEstado_Vuelo` INT NOT NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado_Vuelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vuelo` (
  `idVuelo` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora_Despegue` TIME NOT NULL,
  `Piloto_principal` INT NOT NULL,
  `Copiloto` INT NOT NULL,
  `Avion_Matricula` INT NOT NULL,
  `Ruta_idRuta` INT NOT NULL,
  `Hora_Llegada` TIME NULL,
  `Estado_Vuelo_idEstado_Vuelo` INT NOT NULL,
  PRIMARY KEY (`idVuelo`),
  INDEX `fk_Vuelo_piloto_idx` (`Piloto_principal` ASC) VISIBLE,
  INDEX `fk_Vuelo_piloto1_idx` (`Copiloto` ASC) VISIBLE,
  INDEX `fk_Vuelo_Avion1_idx` (`Avion_Matricula` ASC) VISIBLE,
  INDEX `fk_Vuelo_Ruta1_idx` (`Ruta_idRuta` ASC) VISIBLE,
  INDEX `fk_Vuelo_Estado_Vuelo1_idx` (`Estado_Vuelo_idEstado_Vuelo` ASC) VISIBLE,
  CONSTRAINT `fk_Vuelo_piloto`
    FOREIGN KEY (`Piloto_principal`)
    REFERENCES `mydb`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_piloto1`
    FOREIGN KEY (`Copiloto`)
    REFERENCES `mydb`.`Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Avion1`
    FOREIGN KEY (`Avion_Matricula`)
    REFERENCES `mydb`.`Avion` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Ruta1`
    FOREIGN KEY (`Ruta_idRuta`)
    REFERENCES `mydb`.`Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vuelo_Estado_Vuelo1`
    FOREIGN KEY (`Estado_Vuelo_idEstado_Vuelo`)
    REFERENCES `mydb`.`Estado_Vuelo` (`idEstado_Vuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Ticket` (
  `idEstado_Ticket` INT NOT NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado_Ticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Estado_Ticket_idEstado_Ticket` INT NOT NULL,
  `Precio` DOUBLE NULL,
  `Puesto` INT NOT NULL,
  `Pasajero_idPasajero` INT NOT NULL,
  `Vuelo_idVuelo` INT NOT NULL,
  PRIMARY KEY (`Puesto`, `Pasajero_idPasajero`, `Vuelo_idVuelo`),
  INDEX `fk_Ticket_Estado_Ticket1_idx` (`Estado_Ticket_idEstado_Ticket` ASC) VISIBLE,
  INDEX `fk_Ticket_Pasajero1_idx` (`Pasajero_idPasajero` ASC) VISIBLE,
  INDEX `fk_Ticket_Vuelo1_idx` (`Vuelo_idVuelo` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Estado_Ticket1`
    FOREIGN KEY (`Estado_Ticket_idEstado_Ticket`)
    REFERENCES `mydb`.`Estado_Ticket` (`idEstado_Ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Pasajero1`
    FOREIGN KEY (`Pasajero_idPasajero`)
    REFERENCES `mydb`.`Pasajero` (`idPasajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Vuelo1`
    FOREIGN KEY (`Vuelo_idVuelo`)
    REFERENCES `mydb`.`Vuelo` (`idVuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
